# Generated by Django 4.2 on 2023-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                (
                    "company_prf_bg",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("company_slogam", models.CharField(max_length=50)),
                ("company_location", models.CharField(max_length=50)),
                (
                    "about_us_img",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("about_us_discpt", models.TextField()),
                ("outher_det_title", models.CharField(max_length=50)),
                (
                    "outher_det_image",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("outher_det_discription", models.TextField()),
            ],
        ),
    ]
