# Generated by Django 4.2 on 2023-04-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
        ("company", "0002_companyprofile_rel_comp"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitle", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("posttime", models.DateTimeField(auto_now_add=True)),
                (
                    "jobtype",
                    models.CharField(
                        choices=[("F", "Full Time"), ("P", "Part Time")], max_length=20
                    ),
                ),
                ("last_date", models.CharField(max_length=50)),
                ("price_range", models.CharField(max_length=50)),
                ("vacancy", models.IntegerField()),
                ("job_discription", models.TextField()),
                ("short_discription", models.TextField()),
                ("required", models.TextField()),
                ("education", models.TextField()),
                ("status", models.BooleanField(default=True)),
                (
                    "rel_comp_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.company",
                    ),
                ),
            ],
        ),
    ]
