# Generated by Django 4.2 on 2023-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_jobpost_rel_comp_comp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="jobtype",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                max_length=20,
            ),
        ),
    ]
