# Generated by Django 4.2 on 2023-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_jobpost_jobtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("IT FIELD", "IT FIELD"),
                    ("CUSTOMER SERVICE", "CUSTOMER SERVICE"),
                    ("HUMAN RESOURCE", "HUMAN RESOURCE"),
                    ("WORK FROM HOME", "WORK FROM HOME"),
                    ("MECHANICAL JOBS", "MECHANICAL JOBS"),
                    ("AUTOMOBILE", "AUTOMOBILE"),
                    ("TEACHING & EDUCATION", "TEACHING & EDUCATION"),
                    ("DESIGN & CREATIVE", "DESIGN & CREATIVE"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
