# Generated by Django 4.2 on 2023-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0007_alter_jobpost_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="about_us_discpt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_slogam",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="outher_det_discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="outher_det_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
