# Generated by Django 4.2 on 2023-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
