# Generated by Django 4.2 on 2023-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_account_can_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="active",
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
