# Generated by Django 4.2 on 2023-04-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_remove_account_active_alter_account_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
