# Generated by Django 4.2 on 2023-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_role", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=50)),
                ("job_dicription", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
