# Generated by Django 4.2 on 2023-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddEducations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=50)),
                ("qualification", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=10)),
                ("shor_dicription", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
