# Generated by Django 4.2 on 2023-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_addeducations"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pro_name", models.CharField(max_length=50)),
                ("domine", models.CharField(max_length=50)),
                ("shor_dicription", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
