# Generated by Django 4.2 on 2023-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_addskill"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_title", models.CharField(max_length=50)),
                ("bio", models.TextField()),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile.image/"
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resume/"),
                ),
                ("location", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=12)),
                (
                    "working_sts",
                    models.CharField(
                        choices=[("frsh", "I'm Fresher"), ("exp", "I'm Experienced")],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Outher")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
