# Generated by Django 4.2 on 2023-04-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
        ("employee", "0006_addskill_rel_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addskill",
            name="rel_skill",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.employee",
            ),
        ),
    ]
