# Generated by Django 4.2 on 2023-04-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
        ("employee", "0008_alter_addskill_rel_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="addeducations",
            name="rel_education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.employee",
            ),
        ),
        migrations.AddField(
            model_name="addproject",
            name="rel_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.employee",
            ),
        ),
    ]
