# Generated by Django 4.2 on 2023-04-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
        ("employee", "0009_addeducations_rel_education_addproject_rel_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="addexperience",
            name="rel_experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.employee",
            ),
        ),
    ]
