# Generated by Django 4.2 on 2023-04-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
        ("employee", "0010_addexperience_rel_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileedit",
            name="rel_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.employee",
            ),
        ),
    ]
