# Generated by Django 4.2 on 2023-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_jobpost_jobtype"),
        ("employee", "0011_profileedit_rel_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apply_status", models.BooleanField(default=True)),
                (
                    "rel_profile",
                    models.ManyToManyField(blank=True, null=True, to="company.jobpost"),
                ),
            ],
        ),
    ]
