# Generated by Django 4.2 on 2023-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_company"),
        ("company", "0005_alter_jobpost_jobtype"),
        ("employee", "0012_applyjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="rel_post",
            field=models.ManyToManyField(blank=True, null=True, to="company.jobpost"),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="rel_profile",
            field=models.ManyToManyField(blank=True, null=True, to="account.employee"),
        ),
    ]
