# Generated by Django 4.2 on 2023-04-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_jobpost_jobtype"),
        ("account", "0003_company"),
        ("employee", "0013_applyjob_rel_post_alter_applyjob_rel_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applyjob",
            name="rel_post",
        ),
        migrations.RemoveField(
            model_name="applyjob",
            name="rel_profile",
        ),
        migrations.AddField(
            model_name="applyjob",
            name="rel_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.jobpost",
            ),
        ),
        migrations.AddField(
            model_name="applyjob",
            name="rel_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.employee",
            ),
        ),
    ]
