# Generated by Django 4.2 on 2023-04-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "employee",
            "0014_remove_applyjob_rel_post_remove_applyjob_rel_profile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="rel_empl_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.profileedit",
            ),
        ),
    ]
