# Generated by Django 4.2 on 2023-04-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0015_applyjob_rel_empl_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="selected",
            field=models.CharField(
                choices=[
                    ("Waiting for Review", "Waiting for Review"),
                    ("Your Selected", "Your Selected"),
                    ("Rejected", "Rejected"),
                ],
                default="Waiting for Review",
                max_length=30,
            ),
        ),
    ]
