# Generated by Django 4.2 on 2023-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0017_alter_profileedit_bio_alter_profileedit_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileedit",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                default="static\\img\\pro.png",
                null=True,
                upload_to="profile.image/",
            ),
        ),
    ]
