# Generated by Django 4.2 on 2023-04-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_userotp_user"),
        ("employee", "0018_alter_profileedit_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="company_relation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apply_jobs",
                to="account.company",
            ),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="rel_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applied_jobs",
                to="account.employee",
            ),
        ),
    ]
