# Generated by Django 4.2 on 2023-04-18 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PermissionAllow",
        ),
    ]
